### ISSUE TITLE
ValueError: a must be greater than 0 unless no samples are taken

### ISSUE THREAD

**Issue by magnum-zx** [jvanvugt/pytorch-domain-adaptation#7]
Hello! guys.
Has anyone ever encountered such mistakes?
How the errors fix？

Traceback (most recent call last):
  File "wdgrl.py", line 134, in <module>
    main(args)
  File "wdgrl.py", line 76, in main
    (source_x, source_y), (target_x, _) = next(batch_iterator)
  File "H:\anaconda3\envs\torch1.4\lib\site-packages\torch\utils\data\dataloader.py", line 517, in __next__
    data = self._next_data()
  File "H:\anaconda3\envs\torch1.4\lib\site-packages\torch\utils\data\dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "H:\anaconda3\envs\torch1.4\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "H:\anaconda3\envs\torch1.4\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "G:\pytorch-domain-adaptation\data.py", line 38, in __getitem__
    bsds_image = self._random_bsds_image()
  File "G:\pytorch-domain-adaptation\data.py", line 51, in _random_bsds_image
    i = self.rng.choice(len(self.bsds))
  File "mtrand.pyx", line 902, in numpy.random.mtrand.RandomState.choice
ValueError: a must be greater than 0 unless no samples are taken

**Comment by Learn2Ln** [comment]
The cause of the error is that you don't follow the first step of the "Instructions".
If you download the BSDS500 dataset and extract it at the right folder, this error will not happen. 
Because you have to use the BSDS500 dataset to generate the images of MNISTM.

**Comment by anythingelseting** [comment]
> The cause of the error is that you don't follow the first step of the "Instructions". If you download the BSDS500 dataset and extract it at the right folder, this error will not happen. Because you have to use the BSDS500 dataset to generate the images of MNISTM.

Currently, the website where the original BSDS download link is linked is no longer able to download this dataset. What should I do if the dataset I downloaded from other places still encounters this problem?

**Comment by noisyor** [comment]
Here is an alternative link to download the same:
https://www.kaggle.com/datasets/balraj98/berkeley-segmentation-dataset-500-bsds500?resource=download
